### ISSUE TITLE
dockercompose up -d报错

### ISSUE THREAD

**Issue by apanghu** [someu/aigotools#7]
![Uploading 图片.png…]()

**Comment by apanghu** [comment]
info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
   Collecting page data ...
MongooseServerSelectionError: getaddrinfo ENOTFOUND aigotools-mongo
    at _handleConnectionErrors (/app/node_modules/.pnpm/mongoose@8.8.0/node_modules/mongoose/lib/connection.js:909:11)
    at NativeConnection.openUri (/app/node_modules/.pnpm/mongoose@8.8.0/node_modules/mongoose/lib/connection.js:860:11)
    at async S (/app/.next/server/app/sitemap/[__metadata_id__]/route.js:1:3820)
    at async w (/app/.next/server/app/sitemap/[__metadata_id__]/route.js:1:4496)
    at async Object.M [as generateStaticParams] (/app/.next/server/app/sitemap/[__metadata_id__]/route.js:1:5851)
    at async buildParams (/app/node_modules/.pnpm/next@14.2.16_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.69.7/node_modules/next/dist/build/utils.js:1026:40)
    at async /app/node_modules/.pnpm/next@14.2.16_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.69.7/node_modules/next/dist/build/utils.js:1043:33
    at async /app/node_modules/.pnpm/next@14.2.16_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.69.7/node_modules/next/dist/build/utils.js:1177:114
    at async Span.traceAsyncFn (/app/node_modules/.pnpm/next@14.2.16_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.69.7/node_modules/next/dist/trace/trace.js:154:20) {
  reason: TopologyDescription {
    type: 'Unknown',
    servers: Map(1) { 'aigotools-mongo:27017' => [ServerDescription] },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    setName: null,
    maxElectionId: null,
    maxSetVersion: null,
    commonWireVersion: 0,
    logicalSessionTimeoutMinutes: null
  },
  code: undefined
}

> Build error occurred
Error: Failed to collect page data for /sitemap/[__metadata_id__]
    at /app/node_modules/.pnpm/next@14.2.16_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.69.7/node_modules/next/dist/build/utils.js:1268:15 {
  type: 'Error'
}
 ELIFECYCLE  Command failed with exit code 1.
ERROR: Service 'aigotools' failed to build: The command '/bin/sh -c apk add --no-cache libc6-compat   && npm config set strict-ssl false   && npm config set fetch-retries 10   && corepack enable pnpm   && pnpm i   && mv next.config.docker.js next.config.js   && pnpm run build' returned a non-zero code: 1
